#### 학습목표
- 데이터 조작(잘 꺼내야된다!!) 
- 프레임은 기본 열 인덱스를 사용하고 , 행 인덱스를 위해서는 슬라이싱 
- loc[] 라벨값 , iloc[] 정수값 : 인덱서

In [3]:
import numpy  as np 
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt 
import json   

# warning 제거
import warnings
warnings.filterwarnings('ignore')

# version check 
print('numpy  version - ' , np.__version__)
print('pandas version - ' , pd.__version__)

# 데이터 정보 출력 함수 
def aryInfo(ary) : 
    print('type - ' , type(ary)) 
    print('shape - ' , ary.shape)
    print('ndim  - ' , ary.ndim)
    print('dtype - ' , ary.dtype)
    print()
    print('data  -')
    print(ary) 
    
def seriesInfo(s) :
    print('type   - ' , type(s)) 
    print('index  - ' , s.index)
    print('values - ' , s.values)
    print('dtype  - ' , s.dtype)
    print()
    print('data   - ')
    print(s) 

def frmInfo(frm) :
    print('type    - ' , type(frm))
    print('shape   - ' , frm.shape)
    print('ndim    - ' , frm.ndim)
    print('row idx - ' , frm.index , type(frm.index))
    print('col idx - ' , frm.columns , type(frm.columns))
    print('values  - ' , type(frm.values))
    print(frm.values)
    print('data - ') 
    print(frm)

    

numpy  version -  2.1.3
pandas version -  2.2.3


In [4]:
scores = {
    'kor' : [90, 85, 100, 88, 78],
    'eng' : [90, 85, 100, 88, 78],
    'mat' : [90, 85, 100, 88, 78]
}
frm = pd.DataFrame(scores , 
                   index = ['강승우', '최호준', '임정섭', '이현우', '오신호'])
frmInfo(frm)

type    -  <class 'pandas.core.frame.DataFrame'>
shape   -  (5, 3)
ndim    -  2
row idx -  Index(['강승우', '최호준', '임정섭', '이현우', '오신호'], dtype='object') <class 'pandas.core.indexes.base.Index'>
col idx -  Index(['kor', 'eng', 'mat'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  -  <class 'numpy.ndarray'>
[[ 90  90  90]
 [ 85  85  85]
 [100 100 100]
 [ 88  88  88]
 [ 78  78  78]]
data - 
     kor  eng  mat
강승우   90   90   90
최호준   85   85   85
임정섭  100  100  100
이현우   88   88   88
오신호   78   78   78


In [19]:
frm

,kor,eng,mat,mean
강승우,90,90,90,90.0
최호준,85,85,85,85.0
임정섭,100,100,100,100.0
이현우,88,88,88,88.0
오신호,78,78,78,78.0


In [8]:
# Quiz 
# 모든 학생의 과목평균 점수를 새로운 열('mean') 추가하고 싶다면?
# axis = 0(열) , axis = 1(행) 
frm.values

array([[ 90,  90,  90],
       [ 85,  85,  85],
       [100, 100, 100],
       [ 88,  88,  88],
       [ 78,  78,  78]])

In [20]:
frm['mean'] = np.mean(frm.values , axis = 1).astype(np.int32)
frm

,kor,eng,mat,mean
강승우,90,90,90,90
최호준,85,85,85,85
임정섭,100,100,100,100
이현우,88,88,88,88
오신호,78,78,78,78


In [27]:
# Quiz
# 최호준 학생의 영어점수를 90점으로 수정하고 평균 점수도 다시 계산하고 싶다면
# iloc(), loc()

# frm.loc['최호준', 'eng'] = 90
# frm['mean'] = np.mean(frm.values , axis = 1).astype(np.int32)
# frm

frm['eng']['최호준'] = 75
frm['mean']['최호준'] = np.mean(frm.values[1]).astype(np.int32)
frm

,kor,eng,mat,mean
강승우,90,90,90,90
최호준,85,75,85,82
임정섭,100,100,100,100
이현우,88,88,88,88
오신호,78,78,78,78


In [33]:
lee = frm.loc[['이현우']]
print('type - ' , type(lee))

type -  <class 'pandas.core.frame.DataFrame'>


In [39]:
lim = frm.loc['임정섭']
print('type - ' , type(lim))

type -  <class 'pandas.core.series.Series'>


- titanic dataset(seaborn)

In [41]:
titanicRawData = sns.load_dataset('titanic') 
print('type - ' , type(titanicRawData))

titanicRawData.head()

type -  <class 'pandas.core.frame.DataFrame'>


,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [42]:
titanicRawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [47]:
# Quiz 
# 선실등급(pclass)의 인원수를 확인하고 싶다면?

print('유일값 확인 - unique()')
print(titanicRawData['pclass'].unique())
print(titanicRawData['pclass'].value_counts().values)

유일값 확인 - unique()
[3 1 2]
[491 216 184]


In [50]:
# 데이터 프레임의 컬럼명 확인 
print('type - ' , type(titanicRawData.columns))
print(titanicRawData.columns)

type -  <class 'pandas.core.indexes.base.Index'>
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')


In [55]:
# Quiz
# 기존나이에 10살을 더해서 age_by_10 열을 추가하고 싶다면?
titanicRawData['age_by_10'] = (titanicRawData['age'].values + 10).astype('int')
titanicRawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
 15  age_by_10    891 non-null    int64   
dtypes: bool(2), category(2), float64(2), int64(5), object(5)
memory usage: 87.6+ KB


In [56]:
# age_by_10 컬럼을 삭제하고 싶다면?
# drop( , axis = 1 , inplace = True )  
titanicRawData.drop(['age_by_10'] , axis = 1 , inplace = True) 

In [57]:
titanicRawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [58]:
# 요금(fare)에 대한 통계(최대, 최소, 평균, 합계) 확인인 필요하다면?
print('fare max - ' , np.max(titanicRawData['fare'].values))

fare max -  512.3292


In [63]:
# Quiz
# 선실등급(pclass)이 3등급인 데이터만의 subset 만들고 싶다면?
pclassSubsetFrm = titanicRawData[ titanicRawData['pclass'] == 3 ]
print('type - ' , type(pclassSubsetFrm))
pclassSubsetFrm.head()

type -  <class 'pandas.core.frame.DataFrame'>


,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False


In [64]:
# Quiz
# 위 서브셋에서 성별과(sex), 생존여부(survived)만 가지는 새로운 서브셋을 만들고 싶다면? 
newsubset = pclassSubsetFrm[['sex', 'survived']]
newsubset.head()

,sex,survived
0,male,0
2,female,1
4,male,0
5,male,0
7,male,0


In [65]:
pclassSubsetFrm.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False


In [66]:
# reset_index() 
pclassSubsetFrm.reset_index(inplace = True) 

In [68]:
pclassSubsetFrm

,index,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
2,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
3,5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
4,7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
487,884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
488,885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
489,888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False


In [69]:
pclassSubsetFrm.drop('index' , axis = 1 , inplace = True) 
pclassSubsetFrm

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
2,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
3,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
4,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
487,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
488,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
489,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False


In [70]:
# set_index : 특정 컬럼을 인덱스로 변경하는 함수 
pclassSubsetFrm.reset_index(inplace = True ) 
pclassSubsetFrm

,index,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
2,2,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
3,3,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
4,4,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,486,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
487,487,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
488,488,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
489,489,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False


In [71]:
pclassSubsetFrm.set_index('index' , inplace = True ) 
pclassSubsetFrm

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
index,,,,,,,,,,,,,,,
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
2,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
3,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
4,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
487,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
488,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False


In [79]:
# Quiz 
# 원본 데이터로부터 나이가 60이상이고 선실등급이 1등급이면서 성별이 여자인 데이터만 추출하여 서브셋을 만들고 싶다면?

quizsubset = titanicRawData[ (titanicRawData['age'] >= 60) &
                             (titanicRawData['pclass'] == 1)  & 
                             (titanicRawData['sex'] == 'female') ]
quizsubset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
366,1,1,female,60.0,1,0,75.2500,C,First,woman,False,D,Cherbourg,yes,False
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True


In [81]:
quizsubset = titanicRawData[ (titanicRawData['age'] >= 60) &
                             (titanicRawData['pclass'] == 1)  & 
                             (titanicRawData['sex'] == 'male') ]
quizsubset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
170,0,1,male,61.0,0,0,33.5000,S,First,man,True,B,Southampton,no,True
252,0,1,male,62.0,0,0,26.5500,S,First,man,True,C,Southampton,no,True
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
456,0,1,male,65.0,0,0,26.5500,S,First,man,True,E,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
545,0,1,male,64.0,0,0,26.0000,S,First,man,True,NaN,Southampton,no,True
555,0,1,male,62.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True
587,1,1,male,60.0,1,1,79.2000,C,First,man,True,B,Cherbourg,yes,False


#### sort : 인덱스 기준, 열 값을 기준으로
- sort_index(axis = , ascending = F) 
- sort_values(by  = , ascending = )

In [83]:
# 원본데이터로부터 승객의 나이를 기준으로 내림차순한 서브셋을 만들고 싶다면?
subsetFrm = titanicRawData.sort_values(by='age' , ascending = False)
subsetFrm.reset_index(inplace = True) 
subsetFrm.drop('index' , axis = 1 , inplace = True) 
subsetFrm

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
1,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
2,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
3,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
4,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
887,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
888,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
889,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True


In [86]:
print('성별에 따른 승객수를 시각화하기 위해서 정렬을 한다면 - ') 
titanicRawData['sex'].value_counts().sort_values(ascending = False)

성별에 따른 승객수를 시각화하기 위해서 정렬을 한다면 - 


sex
male      577
female    314
Name: count, dtype: int64

In [87]:
titanicRawData.sort_index(ascending = False ) 

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False


- Pandas 
- csv 파일 입출력과 데이터 조작 (excel, json, html, scraping 비정형 데이터)
- read_xxxxx() , to_xxxxx()

In [103]:
namesFrm = pd.read_csv('./data/year2022_baby_name.csv', 
                      sep      = ',',
                      encoding = 'utf-8') 
print('type - ' , type(namesFrm))

type -  <class 'pandas.core.frame.DataFrame'>


In [104]:
namesFrm.head()

,NAME,GENDER,COUNT
0,Isabella,F,22731
1,Sophia,F,20477
2,Emma,F,17179
3,Olivia,F,16860
4,Ava,F,15300


In [95]:
namesFrm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33838 entries, 0 to 33837
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   NAME    33838 non-null  object
 1   GENDER  33838 non-null  object
 2   COUNT   33838 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 793.2+ KB


In [97]:
# namesFrm.describe()
namesFrm.columns

Index(['NAME', 'GENDER', 'COUNT'], dtype='object')

In [100]:
# Quiz
# count 열을 기준으로 내림차순 정렬하여 서브셋을 만든다면?
# 인덱스를확인하고 reset 시키후 
# 불필요한 'index' 열 삭제 

subset = namesFrm.sort_values(by='COUNT', ascending=False)
subset.reset_index(inplace=True)
subset.drop('index', axis = 1, inplace=True)
subset

,NAME,GENDER,COUNT
0,Isabella,F,22731
1,Jacob,M,21875
2,Sophia,F,20477
3,Ethan,M,17866
4,Emma,F,17179
...,...,...,...
33833,Zadian,M,5
33834,Zacory,M,5
33835,Zacori,M,5
33836,Zishan,M,5


In [120]:
# Quiz 
# 생성한 subset 이용하여 열 이름을 변경하고( NAME -> name , GENDER -> gender , COUNT -> count)
# 성별(gender)이 남자인 데이터만 추출한다면? 

# type( subset.columns.values )

# for col in subset.columns.values : 
#     print(col.lower())

cols = [ col.lower() for col in subset.columns.values]
subset.columns = cols 
# print(cols)

# subset.rename(columns = {col: col.lower() for col in subset.columns}, inplace = True)
subset[subset['gender']=='M']

# subset.rename(columns = cols , inplace = True)
# subset[subset['gender']=='M']

,name,gender,count
1,Jacob,M,21875
3,Ethan,M,17866
5,Michael,M,17133
6,Jayden,M,17030
7,William,M,16870
...,...,...,...
33833,Zadian,M,5
33834,Zacory,M,5
33835,Zacori,M,5
33836,Zishan,M,5


#### 통계량 확인 
- groupby(열 인덱스 | 인덱스 ) : 데이터를 그룹으로 분할하여 독리비된 그룹에 대해서 별도의 데이터 처리 
- split, apply(lambda), combine, agg([count, sum, mean])

In [122]:
frm = pd.read_csv('./data/service_data_groupby_sample.csv' , 
                  encoding = 'cp949') 
frm.head()

,id,gender,height,age,region
0,1,남자,175,22,서울
1,2,여자,160,23,서울
2,3,여자,161,21,서울
3,4,여자,170,33,서울
4,5,여자,155,35,경기


In [123]:
frm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      12 non-null     int64 
 1   gender  12 non-null     object
 2   height  12 non-null     int64 
 3   age     12 non-null     int64 
 4   region  12 non-null     object
dtypes: int64(3), object(2)
memory usage: 612.0+ bytes


In [131]:
# Quiz
# 지역별 나이평균을 확인하고 싶다면?

# type( frm.groupby('region') )
# type( frm.groupby('region').get_group('경기') )
# type( frm.groupby('region').get_group('경기')['age'] )

frm.groupby('region')['age'].mean()

region
경기    32.00
서울    28.25
인천    39.00
충북    33.00
Name: age, dtype: float64

In [136]:
# Quiz
# 성별을 기준으로 그룹을 나누고 싶다면 - 
tmp = frm.groupby('gender')[['height']].mean()
tmp.reset_index(inplace = True) 
tmp

,gender,height
0,남자,180.666667
1,여자,161.500000


In [140]:
# 다중통계량 : agg()

subset = frm.drop('region',axis=1)
subset

,id,gender,height,age
0,1,남자,175,22
1,2,여자,160,23
2,3,여자,161,21
3,4,여자,170,33
4,5,여자,155,35
5,6,남자,181,41
6,7,남자,183,33
7,8,여자,171,22
8,9,남자,188,29
9,10,남자,177,39


In [141]:
subset.groupby('gender').agg(['mean', 'var', 'std'])

id                      height                             age  \
       mean   var       std        mean        var       std       mean   
gender                                                                    
남자      7.5  14.7  3.834058  180.666667  21.066667  4.589844  31.333333   
여자      5.5  11.5  3.391165  161.500000  59.500000  7.713624  29.000000   

                             
              var       std  
gender                       
남자      60.266667  7.763161  
여자      64.400000  8.024961

In [147]:
frm.groupby('gender')['age'].agg(['max', 'min', 'mean', 'median']).reset_index()

,gender,max,min,mean,median
0,남자,41,22,31.333333,31.0
1,여자,40,21,29.000000,28.0


In [153]:
# Quiz
# 성별에 따른 거주지의 최빈값(mode())을 확인하고 싶다면?

# frm.groupby('gender')['region'].agg(lambda x : x.mode() ) 
frm.groupby('gender')['region'].apply(lambda x : x.mode() )

gender   
남자      0    서울
여자      0    서울
Name: region, dtype: object

In [154]:
tipsFrm = sns.load_dataset('tips')
tipsFrm.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [155]:
tipsFrm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [156]:
tipsFrm.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [157]:
titanicFrm = sns.load_dataset('titanic')
titanicFrm.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [174]:
# Quiz
# tipsFrm 전체 평균 팁은 얼마일까요?

print(tipsFrm['tip'].values.mean())
np.mean(tipsFrm['tip'])

2.99827868852459


np.float64(2.99827868852459)

In [171]:
# Quiz
# 남성과 여성 중 평균 팁이 더 높은 성별을 확인하고 싶다면?
print( tipsFrm.groupby('sex')['tip'].agg('mean').reset_index() )
# 흡연자와 비흡연자 중 평균 팁 비율이 높은 그룹은?
# assign() 

print()
print( tipsFrm.assign(pct = tipsFrm['tip'] / tipsFrm['total_bill']).groupby('smoker')['pct'].mean() )

      sex       tip
0    Male  3.089618
1  Female  2.833448

smoker
Yes    0.163196
No     0.159328
Name: pct, dtype: float64


In [183]:
# Quiz
# 팁(tip)금액이 가장 많이 발생하는 요일(day)을 확인하고 싶다면?
result = tipsFrm.groupby('day')['tip'].sum().sort_values(ascending = False).head(1)
print('type' , type(result)  )
print(result)

type <class 'pandas.core.series.Series'>
day
Sat    260.4
Name: tip, dtype: float64


In [192]:
# Quiz
# ['Dinner', 'Lunch'] 중 평균 팁 비율이 높은 시간대를 확인하고 싶다면?
# tipsFrm['time'].unique()

# tipsFrm.groupby('time')['tip'].mean()

tipsFrm['pct'] = tipsFrm['tip'] / tipsFrm['total_bill']

result = tipsFrm.groupby('time')['pct'].mean().sort_values(ascending = False).head(1)
print(result)

time
Lunch    0.164128
Name: pct, dtype: float64


In [194]:
# Quiz : titanicFrm
# subset - (age, sex, class, fare, survived ) 

# subsetTitanic = titanicFrm[['age','sex','class','fare','survived']]
# subsetTitanic.head()

subsetTitanic = titanicFrm.loc[ : , ['age','sex','class','fare','survived']]
subsetTitanic.head()

,age,sex,class,fare,survived
0,22.0,male,Third,7.2500,0
1,38.0,female,First,71.2833,1
2,26.0,female,Third,7.9250,1
3,35.0,female,First,53.1000,1
4,35.0,male,Third,8.0500,0


In [209]:
# Quiz
# 선실등급에 따른 그룹을 만들고 1등급 승객만 데이터 프레임 형식으로 만들 본다면?

# firstClass = subsetTitanic[subsetTitanic['class'] == 'First']
# print( firstClass )

grp = subsetTitanic.groupby('class')
# print(type(grp.get_group('First')))
result = grp.get_group('First') 
print(result)

# print(grp.groups['First'].values)
# subsetTitanic.loc[ grp.groups['First'].values , : ] 


      age     sex  class     fare  survived
1    38.0  female  First  71.2833         1
3    35.0  female  First  53.1000         1
6    54.0    male  First  51.8625         0
11   58.0  female  First  26.5500         1
23   28.0    male  First  35.5000         1
..    ...     ...    ...      ...       ...
871  47.0  female  First  52.5542         1
872  33.0    male  First   5.0000         0
879  56.0  female  First  83.1583         1
887  19.0  female  First  30.0000         1
889  26.0    male  First  30.0000         1

[216 rows x 5 columns]


In [210]:
irisFrm = sns.load_dataset('iris')
irisFrm.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [211]:
irisFrm['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [212]:
grp = irisFrm.groupby('species')
print(grp)

In [213]:
print(grp.groups)

{'setosa': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49], 'versicolor': [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 'virginica': [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]}


In [215]:
for key, group in grp :
    print('key - ' , key)
    print()
    display(group)

key -  setosa



,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa


key -  versicolor



,sepal_length,sepal_width,petal_length,petal_width,species
50,7.0,3.2,4.7,1.4,versicolor
51,6.4,3.2,4.5,1.5,versicolor
52,6.9,3.1,4.9,1.5,versicolor
53,5.5,2.3,4.0,1.3,versicolor
54,6.5,2.8,4.6,1.5,versicolor
55,5.7,2.8,4.5,1.3,versicolor
56,6.3,3.3,4.7,1.6,versicolor
57,4.9,2.4,3.3,1.0,versicolor
58,6.6,2.9,4.6,1.3,versicolor
59,5.2,2.7,3.9,1.4,versicolor


key -  virginica



,sepal_length,sepal_width,petal_length,petal_width,species
100,6.3,3.3,6.0,2.5,virginica
101,5.8,2.7,5.1,1.9,virginica
102,7.1,3.0,5.9,2.1,virginica
103,6.3,2.9,5.6,1.8,virginica
104,6.5,3.0,5.8,2.2,virginica
105,7.6,3.0,6.6,2.1,virginica
106,4.9,2.5,4.5,1.7,virginica
107,7.3,2.9,6.3,1.8,virginica
108,6.7,2.5,5.8,1.8,virginica
109,7.2,3.6,6.1,2.5,virginica


In [221]:
irisFrm.sort_values(by='petal_length' , ascending = False ).groupby('species').get_group('setosa')

,sepal_length,sepal_width,petal_length,petal_width,species
24,4.8,3.4,1.9,0.2,setosa
44,5.1,3.8,1.9,0.4,setosa
18,5.7,3.8,1.7,0.3,setosa
5,5.4,3.9,1.7,0.4,setosa
23,5.1,3.3,1.7,0.5,setosa
20,5.4,3.4,1.7,0.2,setosa
30,4.8,3.1,1.6,0.2,setosa
46,5.1,3.8,1.6,0.2,setosa
11,4.8,3.4,1.6,0.2,setosa
25,5.0,3.0,1.6,0.2,setosa


In [222]:
titanicFrm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [225]:
print('age 결측값 - ')
print( titanicFrm['age'].isnull().sum() )

age 결측값 - 
177


In [233]:
# titanicFrm.groupby('sex')['age'].mean()
titanicFrm.groupby('sex')['age'].groups

{'female': [1, 2, 3, 8, 9, 10, 11, 14, 15, 18, 19, 22, 24, 25, 28, 31, 32, 38, 39, 40, 41, 43, 44, 47, 49, 52, 53, 56, 58, 61, 66, 68, 71, 79, 82, 84, 85, 88, 98, 100, 106, 109, 111, 113, 114, 119, 123, 128, 132, 133, 136, 140, 141, 142, 147, 151, 156, 161, 166, 167, 172, 177, 180, 184, 186, 190, 192, 194, 195, 198, 199, 205, 208, 211, 215, 216, 218, 229, 230, 233, 235, 237, 240, 241, 246, 247, 251, 254, 255, 256, 257, 258, 259, 264, 268, 269, 272, 274, 275, 276, ...], 'male': [0, 4, 5, 6, 7, 12, 13, 16, 17, 20, 21, 23, 26, 27, 29, 30, 33, 34, 35, 36, 37, 42, 45, 46, 48, 50, 51, 54, 55, 57, 59, 60, 62, 63, 64, 65, 67, 69, 70, 72, 73, 74, 75, 76, 77, 78, 80, 81, 83, 86, 87, 89, 90, 91, 92, 93, 94, 95, 96, 97, 99, 101, 102, 103, 104, 105, 107, 108, 110, 112, 115, 116, 117, 118, 120, 121, 122, 124, 125, 126, 127, 129, 130, 131, 134, 135, 137, 138, 139, 143, 144, 145, 146, 148, 149, 150, 152, 153, 154, 155, ...]}

In [241]:
tmp = titanicFrm.groupby('sex')['age'].apply(lambda x : x.fillna(x.mean()))
print(type(tmp))

<class 'pandas.core.series.Series'>


In [243]:
titanicFrm['age'] = tmp.values
print('age 결측값 - ')
print( titanicFrm['age'].isnull().sum() )

age 결측값 - 
0
